### ISSUE TITLE
执行build.sh部署时报bug

### ISSUE THREAD

**Issue by scoutys** [Shangyizhou/A-Tiny-Network-Library#1]
CMake Error at CMakeLists.txt:62 (add_subdirectory):
  The source directory

    /home/zhang/文档/project/tiny-network/example

  does not contain a CMakeLists.txt file.

**Comment by Shangyizhou** [comment]
> CMake Error at CMakeLists.txt:62 (add_subdirectory): The source directory
> 
> ```
> /home/zhang/文档/project/tiny-network/example
> ```
> 
> does not contain a CMakeLists.txt file.

该项目的根目录下的 CMakeLists.txt 会加载 example 目录的 CMakeLists.txt，但是我当时似乎删除了 example 目录下的 CMakeLists.txt，你可以先试着注释掉根目录下 CMakeLists.txt 的 62 行，然后再重新编译。
